# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MacOS NodeJS-CMake
env:
  DMG_OUTPUT: ${{github.workspace}}${{ '/out/make/zip/darwin/arm64'}}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'
    
    - name: Use cmake
      run: cmake --version

    - name: Checkout Action
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install nodejs dependencies
      run: npm i
    
    - name: Build
      run: npm run make

    - name: Self-sign - Avoid Gatekeeper DMG corrupted warning
      run: |
        echo "Unzipping"
        unzip -q ${{ env.DMG_OUTPUT }}/Playful*.zip -d ${{ env.DMG_OUTPUT }}
        echo "Removing zip"
        rm -rf ${{ env.DMG_OUTPUT }}/Playful*.zip
        echo "Codesigning"
        codesign --force --deep -s - ${{ env.DMG_OUTPUT }}/Playful.app
        echo "Zipping"
        cd ${{ env.DMG_OUTPUT }} && zip -q -r Playful_apple_silicon.zip Playful.app
        echo "Removing .app"
        rm -rf ${{ env.DMG_OUTPUT }}/Playful.app
    
    - name: Upload Build File
      uses: actions/upload-artifact@v4
      with:
        name: Playful-darwin-amd64
        path: ${{ env.DMG_OUTPUT }}/Playful_apple_silicon.zip
