# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MacOS NodeJS-CMake
env:
  DMG_OUTPUT: ${{github.workspace}}/${{ 'Playful/out/make/zip/darwin/*64/'}}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'
    
    - name: Use cmake
      run: cmake --version

    - name: Checkout Action
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install nodejs dependencies
      run: npm i
    
    - name: Build
      run: npm run make

    - name: Self-sign - Avoid Gatekeeper DMG corrupted warning
      run: |
        pwd
        ls
        cd /Users/runner/work/Playful/Playful/Playful/out/make/zip/darwin/ && ls
        unzip ${{ env.DMG_OUTPUT }}/Playful*.zip
        rm -rf ${{ env.DMG_OUTPUT }}/Playful*.zip
        codesign --force --deep -s ${{ env.DMG_OUTPUT }}/Playful.app
        zip ${{ env.DMG_OUTPUT }}/Playful-apple-silicon.zip ${{ env.DMG_OUTPUT }}/Playful.app
        rm -rf ${{ env.DMG_OUTPUT }}/Playful.app
    
    - name: Upload Build File
      uses: actions/upload-artifact@v4
      with:
        name: Playful-darwin-amd64
        path: /Users/runner/work/Playful/Playful/out/make
